#!/usr/bin/env bun

/**
 * Extracts GraphQL document nodes from the generated queries.ts file
 * by evaluating them as JavaScript (needed because documents contain
 * spread references to fragment definitions like ...FragmentDoc.definitions).
 *
 * Outputs:
 *   1. A JSON map of { documentName: documentAST } served at runtime
 *   2. A TypeScript type map for compile-time type safety + autocomplete
 *
 * Usage: bun extract-documents.ts <input-queries.ts> <output-documents.json>
 */

import * as fs from "fs";
import * as path from "path";

export interface ConstLine {
  name: string;
  expression: string;
}

export interface TypeInfo {
  queryType: string;
  variablesType: string;
}

export type TypeInfoMap = Record<string, TypeInfo>;

export interface ParseResult {
  constLines: ConstLine[];
  typeInfoMap: TypeInfoMap;
}

export function parseConstants(content: string): ParseResult {
  const constLines: ConstLine[] = [];
  const typeInfoMap: TypeInfoMap = {};

  const constRegex =
    /^export const (\w+(?:Document|FragmentDoc))\s*=\s*(.+?) as unknown as .+;$/gm;
  const typeRegex =
    /^export const (\w+Document)\s*=\s*.+? as unknown as DocumentNode<(\w+),\s*(\w+)>;$/gm;

  let match;
  while ((match = constRegex.exec(content)) !== null) {
    constLines.push({ name: match[1], expression: match[2] });
  }

  let typeMatch;
  while ((typeMatch = typeRegex.exec(content)) !== null) {
    typeInfoMap[typeMatch[1]] = {
      queryType: typeMatch[2],
      variablesType: typeMatch[3],
    };
  }

  return { constLines, typeInfoMap };
}

export function buildEvalScript(constLines: ConstLine[]): string {
  let evalScript = "const _exports = {};\n";

  for (const { name, expression } of constLines) {
    evalScript += `const ${name} = ${expression};\n`;
  }

  for (const { name } of constLines) {
    if (name.endsWith("Document")) {
      evalScript += `_exports["${name}"] = ${name};\n`;
    }
  }

  evalScript += "_exports;\n";
  return evalScript;
}

export function evaluateDocuments(
  evalScript: string,
): Record<string, unknown> {
  return eval(evalScript) as Record<string, unknown>;
}

export function generateTypeMap(
  typeInfoMap: TypeInfoMap,
  documentNames: string[],
): string {
  const typedDocuments = documentNames.filter((name) => typeInfoMap[name]);

  if (typedDocuments.length === 0) {
    return "";
  }

  let typeFile = `/* eslint-disable */\n// THIS FILE IS GENERATED by extract-documents.ts, DO NOT EDIT!\n`;
  typeFile += `import type { TypedDocumentNode } from "@graphql-typed-document-node/core";\n`;

  const typeImports = new Set<string>();
  for (const name of typedDocuments) {
    const info = typeInfoMap[name];
    typeImports.add(info.queryType);
    typeImports.add(info.variablesType);
  }

  typeFile += `import type {\n`;
  typeFile += Array.from(typeImports)
    .sort()
    .map((t) => `  ${t},`)
    .join("\n");
  typeFile += `\n} from "./queries";\n\n`;

  typeFile += `export interface DocumentMap {\n`;
  for (const name of typedDocuments) {
    const info = typeInfoMap[name];
    typeFile += `  ${name}: TypedDocumentNode<${info.queryType}, ${info.variablesType}>;\n`;
  }
  typeFile += `}\n\n`;

  typeFile += `export type DocumentName = keyof DocumentMap;\n`;

  return typeFile;
}

// CLI entry point
if (
  typeof process !== "undefined" &&
  process.argv[1] &&
  process.argv[1].includes("extract-documents")
) {
  const inputFile = process.argv[2];
  const outputFile = process.argv[3];

  if (!inputFile || !outputFile) {
    console.error(
      "Usage: bun extract-documents.ts <input-queries.ts> <output-documents.json>",
    );
    process.exit(1);
  }

  const content = fs.readFileSync(inputFile, "utf-8");

  const { constLines, typeInfoMap } = parseConstants(content);
  console.log(`Found ${constLines.length} document/fragment constants`);

  const evalScript = buildEvalScript(constLines);

  let documents: Record<string, unknown>;
  try {
    documents = evaluateDocuments(evalScript);
  } catch (e) {
    console.error(
      `Failed to evaluate document constants: ${(e as Error).message}`,
    );
    const lines = evalScript.split("\n");
    for (let i = 0; i < lines.length; i++) {
      try {
        eval(lines.slice(0, i + 1).join("\n"));
      } catch (innerErr) {
        console.error(
          `Error at line ${i + 1}: ${lines[i].substring(0, 100)}`,
        );
        console.error(`  ${(innerErr as Error).message}`);
        break;
      }
    }
    process.exit(1);
  }

  const count = Object.keys(documents).length;
  const jsonOutput = JSON.stringify(documents);

  fs.writeFileSync(outputFile, jsonOutput);

  const sizeMB = (Buffer.byteLength(jsonOutput) / 1048576).toFixed(1);
  console.log(
    `Extracted ${count} document nodes -> ${outputFile} (${sizeMB} MB)`,
  );

  const documentNames = Object.keys(documents);
  const typeMapContent = generateTypeMap(typeInfoMap, documentNames);

  if (typeMapContent) {
    const typeMapPath = path.join(path.dirname(inputFile), "document-map.ts");
    fs.writeFileSync(typeMapPath, typeMapContent);
    const typedCount = documentNames.filter(
      (name) => typeInfoMap[name],
    ).length;
    console.log(
      `Generated type map with ${typedCount} typed documents -> ${typeMapPath}`,
    );
  }
}
